Remove #![feature(non_ascii_idents)] after 1.53.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> tests/to_hiragana.rs:1:1
  |
1 | #![feature(non_ascii_idents)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
  |
  = help: the feature `non_ascii_idents` has been stable since 1.53.0 and no longer requires an attribute to enable